dashboard:
  container_name: havira-location
  image: havira-location
  depends_on:
    - postgres
  build:
    context: ../../packages/havira-location
    dockerfile: Dockerfile
  ports:
    - "5173:5173"
  volumes:
    - ../../packages/havira-location:/app
    - node_modules:/app/node_modules
volumes:
  pgdata: {}
  node_modules: {}
